version: '2'
services:
    global_gateway:
        container_name: global_gateway
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/log:/var/log/nginx"
        networks:
            - default
            - app1_default
            - app2_default
        external_links:
            - "app1_nginx"
            - "app2_nginx"

networks:
  default:
      driver: bridge
  app1_default:
      external: true
  app2_default:
      external: true
