version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/log:/var/log/nginx"
            - "./src:/application"
        links:
            - "backend"

    backend:
        build:
            context: ./containers/php7
        restart: always
        volumes:
            - "./src:/application"
        links:
            - "database"

    database:
        image: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=default
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=default
            - MYSQL_PASSWORD=default
        ports:
            - 3307:3306
        volumes:
            - ./data/db/mysql_default:/var/lib/mysql