version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        restart: always
        volumes:
            - "./files/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./files/index.html:/application/index.html"

